const IDENTIFIER_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

function escapeLuaString(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t')
        .replace(/"/g, '\\"');
}

function formatKey(key: string): string {
    if (IDENTIFIER_RE.test(key)) {
        return key;
    }
    return `["${escapeLuaString(key)}"]`;
}

function serializeValue(value: unknown, indent: number): string {
    if (value === null || value === undefined) {
        return 'nil';
    }

    if (typeof value === 'boolean') {
        return value ? 'true' : 'false';
    }

    if (typeof value === 'number') {
        if (!Number.isFinite(value)) {
            return 'nil';
        }
        return String(value);
    }

    if (typeof value === 'string') {
        return `"${escapeLuaString(value)}"`;
    }

    if (Array.isArray(value)) {
        if (value.length === 0) {
            return '{}';
        }

        const childIndent = indent + 1;
        const pad = '  '.repeat(childIndent);
        const lines = value.map((item) => `${pad}${serializeValue(item, childIndent)}`);
        return `{\n${lines.join(',\n')}\n${'  '.repeat(indent)}}`;
    }

    if (typeof value === 'object') {
        const entries = Object.entries(value as Record<string, unknown>);
        if (entries.length === 0) {
            return '{}';
        }

        const childIndent = indent + 1;
        const pad = '  '.repeat(childIndent);
        const lines = entries.map(
            ([key, v]) => `${pad}${formatKey(key)} = ${serializeValue(v, childIndent)}`,
        );

        return `{\n${lines.join(',\n')}\n${'  '.repeat(indent)}}`;
    }

    return 'nil';
}

export function jsonToLuaTable(value: unknown, indent = 0): string {
    return serializeValue(value, indent);
}

export function buildNHFDataLua(data: unknown): string {
    return `-- Generated by NHF Addon Manager. Do not edit manually.
NHFData = ${jsonToLuaTable(data)}
`;
}
